function fig = tpi_53()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load tpi_53

h0 = figure('Color',[0.5 0.7 1], ...
	'Colormap',mat0, ...
	'FileName','C:\dsf\Trabajo\p1_mcc\tpi_53.m', ...
	'Name','Trabajo Práctico _  Motor Corriente Continua', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[86 51 488 426], ...
	'Tag','TPI', ...
	'ToolBar','none');
h1 = uimenu('Parent',h0, ...
	'Callback','                      ', ...
	'Interruptible','off', ...
	'Label','File', ...
	'Tag','FigMenuFile', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Close', ...
	'Tag','FigMenuFileClose', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Save Figure', ...
	'Tag','FigMenuFileSaveFigure', ...
	'UserData','C:\dsf\Trabajo\p1_mcc\tpi_03.m', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Save Figure As...', ...
	'Tag','FigMenuFileSaveFigureAs', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Print...', ...
	'Separator','on', ...
	'Tag','FigMenuFilePrint', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'Callback','                      ', ...
	'Interruptible','off', ...
	'Label','Edit', ...
	'Tag','FigMenuEdit', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Undo', ...
	'Tag','FigMenuEditUndo', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','                      ', ...
	'Interruptible','off', ...
	'Label','Add Object', ...
	'Tag','FigMenuEditAdd', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','axes', ...
	'Tag','FigMenuEditAddaxes', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','text', ...
	'Tag','FigMenuEditAddtext', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','listbox', ...
	'Tag','FigMenuEditAddlistbox', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','checkbox', ...
	'Tag','FigMenuEditAddcheckbox', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','slider', ...
	'Tag','FigMenuEditAddslider', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','pushbutton', ...
	'Tag','FigMenuEditAddpushbutton', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','edit', ...
	'Tag','FigMenuEditAddedit', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','popupmenu', ...
	'Tag','FigMenuEditAddpopupmenu', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','radiobutton', ...
	'Tag','FigMenuEditAddradiobutton', ...
	'Visible','off');
h3 = uimenu('Parent',h2, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','frame', ...
	'Tag','FigMenuEditAddframe', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'Accelerator','x', ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Cut', ...
	'Tag','FigMenuEditCut', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'Accelerator','c', ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Copy', ...
	'Tag','FigMenuEditCopy', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'Accelerator','v', ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Paste', ...
	'Tag','FigMenuEditPaste', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Delete', ...
	'Tag','FigMenuEditDelete', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'Callback','                      ', ...
	'Interruptible','off', ...
	'Label','Options', ...
	'Tag','FigMenuOptions', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Activate Figure', ...
	'Tag','FigMenuOptionsActivate', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Bring To Front', ...
	'Separator','on', ...
	'Tag','FigMenuOptionsBringFront', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel FigMenuCall  ', ...
	'Interruptible','off', ...
	'Label','Send To Back', ...
	'Tag','FigMenuOptionsSendBack', ...
	'Visible','off');
h1 = uimenu('Parent',h0, ...
	'Callback','                      ', ...
	'Interruptible','off', ...
	'Label','Tools', ...
	'Tag','MenuTools', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel ToolsMenuCall', ...
	'Interruptible','off', ...
	'Label','Control Panel', ...
	'Tag','MenuToolsControlPanel', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel ToolsMenuCall', ...
	'Interruptible','off', ...
	'Label','Property Editor', ...
	'Tag','MenuToolsPropEdit', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel ToolsMenuCall', ...
	'Interruptible','off', ...
	'Label','Callback Editor', ...
	'Tag','MenuToolsCbEdit', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel ToolsMenuCall', ...
	'Interruptible','off', ...
	'Label','Alignment Tool', ...
	'Tag','MenuToolsAligner', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel ToolsMenuCall', ...
	'Interruptible','off', ...
	'Label','Menu Editor', ...
	'Tag','MenuToolsMenuEdit', ...
	'Visible','off');
h2 = uimenu('Parent',h1, ...
	'Accelerator','r', ...
	'ButtonDownFcn','ctlpanel SelectMoveResize', ...
	'Callback','ctlpanel ToolsMenuCall', ...
	'Interruptible','off', ...
	'Label','Refresh Tools', ...
	'Separator','on', ...
	'Tag','MenuOptionsUpdate', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[158.25 53.25 130.5 146.25], ...
	'Style','frame', ...
	'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.95 1], ...
	'Callback',mat1, ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Max',4, ...
	'Min',64, ...
	'Position',[20.25 263.25 111.75 13.5], ...
	'String',['A (EI_MCC)              ';'B (IP_MCC)              ';'INDUCCIÓN TRIFÁSICO     ';'                        ';'                        '], ...
	'Style','popupmenu', ...
	'Tag','popup_motor', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.7 1], ...
	'Enable','inactive', ...
	'FontSize',10, ...
	'FontWeight','demi', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[12 288.75 58.5 12.75], ...
	'String',' Motor :', ...
	'Style','text', ...
	'Tag','Titulo Motores');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[230.25 173.25 44.25 18], ...
	'Style','text', ...
	'Tag','fijo1', ...
	'Value',[]);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.97 1], ...
	'Enable','off', ...
	'ForegroundColor',[0.15 0.3 0], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[232.5 174.75 48.75 15.75], ...
	'Style','edit', ...
	'Tag','variable1', ...
	'Visible','off');
h1 = axes('Parent',h0, ...
    'Box','on',...
	'Units','points', ...
	'CameraPosition',[32.5 32.5 9.16025], ...
	'CameraPositionMode','manual', ...
	'CameraTarget',[32.5 32.5 0.5], ...
	'CameraTargetMode','manual', ...
	'CameraUpVector',[0 -1 0], ...
	'CameraUpVectorMode','manual', ...
	'CameraViewAngle',6.60861, ...
	'CameraViewAngleMode','manual', ...
	'CLim',[31 255], ...
	'CLimMode','manual', ...
	'Color',[0.77 0.77 0.77], ...
	'ColorOrder',mat2, ...
	'DataAspectRatio',[64 64 1], ...
	'DataAspectRatioMode','manual', ...
	'Interruptible','off', ...
	'Layer','top', ...
	'Position',[321 163.5 30.75 27], ...
	'Tag','image_datos', ...
	'UserData',129.001, ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 64.5], ...
	'XLimMode','manual', ...
	'XTickLabel',['20';'40';'60'], ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 64.5], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = image('Parent',h1, ...
	'ButtonDownFcn','simulaciones,set(findobj(''Tag'',''image_scope''),''Visible'',''on'')', ...
	'CData',mat3, ...
	'Interruptible','off', ...
	'Tag','image_dato', ...
	'XData',[1 64], ...
	'YData',[1 64]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Interruptible','off', ...
	'Position',[30.67142952391816 79.12854714008665 9.16025], ...
	'Tag','image_datosText4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Interruptible','off', ...
	'Position',[-13.21426190204579 35.24285571412275 9.16025], ...
	'Rotation',90, ...
	'Tag','image_datosText3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Interruptible','off', ...
	'Position',[-788.5281437607422 -312.1855347414252 9.16025], ...
	'Tag','image_datosText2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Interruptible','off', ...
	'Position',[30.6714 -12.3 0], ...
	'Tag','image_datosText1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[165 171.75 61.5 18], ...
	'Style','text', ...
	'Tag','etiqueta1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.97 1], ...
	'ForegroundColor',[0.15 0.3 0], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[233.25 152.25 48 16.5], ...
	'Style','edit', ...
	'Tag','variable2', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','off', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[231 150.75 51 18], ...
	'Style','text', ...
	'Tag','fijo2', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[18 53.25 115.5 174.75], ...
	'Style','frame', ...
	'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.5 0.7 1], ...
	'Enable','inactive', ...
	'FontSize',10, ...
	'FontWeight','bold', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[148.5 287.25 85.5 12.75], ...
	'String','Simulación :', ...
	'Style','text', ...
	'Tag','Titulo Simulacion');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[36.75 180.75 36 16.5], ...
	'String','Uan:', ...
	'Style','text', ...
	'Tag','parametro1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[36.75 140.25 36 16.5], ...
	'String','Wn :', ...
	'Style','text', ...
	'Tag','parametro3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[36.75 119.25 36 16.5], ...
	'String','La :', ...
	'Style','text', ...
	'Tag','parametro4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[36.75 99 36 16.5], ...
	'String','Ra :', ...
	'Style','text', ...
	'Tag','parametro5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[36.75 78.75 36 16.5], ...
	'String','Uen:', ...
	'Style','text', ...
	'Tag','parametro6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[36.75 56.75 36 16.5], ...
	'String','Re :', ...
	'Style','text', ...
	'Tag','parametro7');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[165 150.75 61.5 18], ...
	'Style','text', ...
	'Tag','etiqueta2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[165 129.75 61.5 18], ...
	'Style','text', ...
	'Tag','etiqueta3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[165 106.5 63.75 18], ...
	'Style','text', ...
	'Tag','etiqueta4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','off', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[233.25 129.75 45 18], ...
	'Style','text', ...
	'Tag','fijo3', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[233.25 107.25 45 18], ...
	'Style','text', ...
	'Tag','fijo4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.97 1], ...
	'ForegroundColor',[0 0.15 0.3], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[232.5 130.5 48.75 15.75], ...
	'Style','edit', ...
	'Tag','variable3', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.97 1], ...
	'Enable','off', ...
	'ForegroundColor',[0.15 0.3 0], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[233.25 107.25 48 15.75], ...
	'Style','edit', ...
	'Tag','variable4', ...
	'Visible','off');
h1 = axes('Parent',h0, ...
	'Units','points', ...
	'AmbientLightColor',[0 0 0], ...
	'Box','on', ...
	'CameraPosition',[32.5 32.5 9.16025], ...
	'CameraPositionMode','manual', ...
	'CameraTarget',[32.5 32.5 0.5], ...
	'CameraTargetMode','manual', ...
	'CameraUpVector',[0 -1 0], ...
	'CameraUpVectorMode','manual', ...
	'CameraViewAngle',6.60861, ...
	'CameraViewAngleMode','manual', ...
	'CLim',[31 255], ...
	'CLimMode','manual', ...
	'Color',[0.77 0.77 0.77], ...
	'ColorOrder',mat4, ...
	'Interruptible','off', ...
	'Layer','top', ...
	'PlotBoxAspectRatioMode','manual', ...
	'Position',[319.5 72 29.25 28.5], ...
	'Tag','image_graficas', ...
	'TickDirMode','manual', ...
	'UserData',[], ...
	'Visible','on', ...
	'WarpToFill','off', ...
	'WarpToFillMode','manual', ...
	'XColor',[0 0 0], ...
	'XLim',[0.5 64.5], ...
	'XLimMode','manual', ...
	'XTickLabel',['20';'40';'60'], ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YDir','reverse', ...
	'YLim',[0.5 64.5], ...
	'YLimMode','manual', ...
	'YTickLabelMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0], ...
	'ZLimMode','manual', ...
	'ZTick',[0 0.5 1], ...
	'ZTickLabelMode','manual', ...
	'ZTickMode','manual');
h2 = image('Parent',h1, ...
	'ButtonDownFcn',mat5, ...
	'CData',mat6, ...
	'Tag','image_scope', ...
	'Visible','on', ...
	'XData',[1 64], ...
	'YData',[1 64]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[30.77027117127386 78.3378139612405 9.16025], ...
	'Tag','Text8', ...
	'VerticalAlignment','cap', ...
	'Visible','off');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',mat7, ...
	'Rotation',90, ...
	'Tag','Text7', ...
	'VerticalAlignment','baseline', ...
	'Visible','off');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-738.9590576118213 -502.8510724907145 9.16025], ...
	'Tag','Text6', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[30.7703 -11.6081 0], ...
	'Tag','Text5', ...
	'VerticalAlignment','bottom', ...
	'Visible','off');
set(get(h2,'Parent'),'Title',h2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.95 1], ...
	'Callback','set_simulacion', ...
	'Enable','off', ...
	'FontName','Arial', ...
	'FontSize',7, ...
	'Position',[158.25 207 131.25 69], ...
	'String',['1) Diseño A Rotor Bloqueado                                       ';'2) Rotor Bloqueado, PR(PT1)                                       ';'3) Rotor Bloqueado, PR(Tiempo Muerto)                             ';'4) Rotor Bloqueado, PR(Tiempo Muerto), con escalón de fem         ';'5) DB Motor Completo                                              ';'6) DB Motor Completo, con cupla de fricción                       ';'                                                                  ';'                                                                  ';'9) Lazo de corriente como PT1,DB Rotor Bloqueado PR(Tiempo Muerto)'], ...
	'Style','listbox', ...
	'Tag','ListaSim_B', ...
	'Value',6, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.97 1], ...
	'Enable','off', ...
	'ForegroundColor',[0 0.15 0.3], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[232.5 83.25 48 15.75], ...
	'Style','edit', ...
	'Tag','variable5', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','off', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[231 82.5 50.25 18], ...
	'Style','text', ...
	'Tag','fijo5', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[165 82.5 60.75 18], ...
	'Style','text', ...
	'Tag','etiqueta5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[165 55.5 62.25 18], ...
	'Style','text', ...
	'Tag','etiqueta6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.97 1], ...
	'Enable','off', ...
	'ForegroundColor',[0.15 0.3 0], ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[232.5 60 48 15.75], ...
	'Style','edit', ...
	'Tag','variable6', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','off', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[231.75 58.5 51 18], ...
	'Style','text', ...
	'Tag','fijo6', ...
	'Value',[], ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.95 1], ...
	'Callback','set_simulacion', ...
	'FontName','Arial', ...
	'FontSize',7, ...
	'ListboxTop',6, ...
	'Position',[158.25 207 131.25 69], ...
	'String',mat8, ...
	'Style','listbox', ...
	'Tag','ListaSim_A', ...
	'Value',11);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'FontName','Symbol', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[181.5 150.75 41.25 18], ...
	'String','( x = Ö2) =', ...
	'Style','text', ...
	'Tag','parche2', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontName','Symbol', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[180 127.5 39.75 20.25], ...
	'String','( x = Ö2) =', ...
	'Style','text', ...
	'Tag','parche3', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.95 1], ...
	'Callback','set_simulacion', ...
	'Enable','off', ...
	'FontName','Arial', ...
	'FontSize',7, ...
	'Position',[158.25 207 131.25 69], ...
	'String',['1) PWM, llaves ideales          ';'2) PWM, llaves ideales          ';'3) PWM, llaves con tiempo muerto';'4) PWM, llaves con tiempo muerto';'5) PWM, compensado              ';'                                ';'                                ';'                                '], ...
	'Style','listbox', ...
	'Tag','ListaSim_MI', ...
	'Value',5, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 57 39.75 16.5], ...
	'String','25.2 ohm', ...
	'Style','text', ...
	'Tag','renglon7');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 78.75 39.75 16.5], ...
	'String','184 V', ...
	'Style','text', ...
	'Tag','renglon6');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 99 39.75 16.5], ...
	'String','0.05 ohm', ...
	'Style','text', ...
	'Tag','renglon5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 119.25 39.75 16.5], ...
	'String','3 mH', ...
	'Style','text', ...
	'Tag','renglon4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 140.25 39.75 16.5], ...
	'String','65.44rad/s', ...
	'Style','text', ...
	'Tag','renglon3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 180.75 39.75 16.5], ...
	'String','460 V', ...
	'Style','text', ...
	'Tag','renglon1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 160.5 39.75 16.5], ...
	'String','320 A', ...
	'Style','text', ...
	'Tag','renglon2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[78 201 39.75 16.5], ...
	'String','147.2 KW', ...
	'Style','text', ...
	'Tag','renglon0');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontSize',9, ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[37.5 201.75 36 16.5], ...
	'String','Pnom:', ...
	'Style','text', ...
	'Tag','parametro0');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.75 0.85 1], ...
	'Enable','inactive', ...
	'FontWeight','demi', ...
	'HorizontalAlignment','left', ...
	'Interruptible','off', ...
	'ListboxTop',0, ...
	'Position',[37.5 159.75 36 16.5], ...
	'String','Ian:', ...
	'Style','text', ...
	'Tag','parametro2');
if nargout > 0, fig = h0; end
